[build]
  command = "rm -rf node_modules && rm -f package-lock.json && npm install --legacy-peer-deps && npm run build"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "v20.15.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"

# Handle signal data
[[redirects]]
  from = "/latest-signal.json"
  to = "/.netlify/functions/poll-openai"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-gatsby"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["fs", "path", "crypto", "stream", "stream/web", "util", "buffer", "process", "events", "http", "https", "url", "zlib", "net", "tls", "dns", "dgram", "child_process", "cluster", "os", "vm", "v8", "perf_hooks", "async_hooks", "timers", "string_decoder", "querystring", "punycode", "readline", "repl", "module", "assert", "constants", "domain"]

[[scheduled]]
  id = "poll-openai"
  function = "poll-openai"
  cron = "0 * * * *" # every hour