[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "public"
  functions = "netlify/functions"
  edge_functions = "netlify/edge-functions"

[build.environment]
  NODE_VERSION = "v20.15.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-gatsby"

# Handle static assets first
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/page-data/*"
  to = "/page-data/:splat"
  status = 200
  force = true

# Handle JavaScript files with proper MIME type
[[redirects]]
  from = "/app-*.js"
  to = "/app-:splat"
  status = 200
  force = true
  headers = { Content-Type = "application/javascript" }

[[redirects]]
  from = "/framework-*.js"
  to = "/framework-:splat"
  status = 200
  force = true
  headers = { Content-Type = "application/javascript" }

[[redirects]]
  from = "/webpack-runtime-*.js"
  to = "/webpack-runtime-:splat"
  status = 200
  force = true
  headers = { Content-Type = "application/javascript" }

[[redirects]]
  from = "/commons-*.js"
  to = "/commons-:splat"
  status = 200
  force = true
  headers = { Content-Type = "application/javascript" }

# Handle signal data
[[redirects]]
  from = "/latest-signal.json"
  to = "/.netlify/edge-functions/signal-handler"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Handle all other routes last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["fs", "path", "crypto", "stream", "stream/web", "util", "buffer", "process", "events", "http", "https", "url", "zlib", "net", "tls", "dns", "dgram", "child_process", "cluster", "os", "vm", "v8", "perf_hooks", "async_hooks", "timers", "string_decoder", "querystring", "punycode", "readline", "repl", "module", "assert", "constants", "domain"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval'; img-src 'self' https: data:;"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/page-data/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[scheduled]]
  id = "poll-openai"
  function = "poll-openai"
  cron = "0 * * * *" # every hour


